---

postgres_password: "{{ vault_postgres_password }}"
postgres_user: "discourse"
postgres_db: "discourse"


grafana:
  host: "metrics.parkourvienna.at"

discourse:
  site_domain: parkourvienna.at
  admin_emails: "{{ vault_admin_emails }}"
  smtp:
    address: smtp.eu.mailgun.org
    username: pkv@mg.parkourvienna.at
    password: "{{ vault_smtp_password }}"

acme_email: "{{ vault_acme_email }}"

