all:
  hosts:
    parkourvienna.at:
      ansible_host: 152.89.244.75 
      ansible_user: root
      ansible_port: 2020
      ansible_python_interpreter: /usr/bin/python3
  children:
    production:
      hosts:
        parkourvienna.at: {}
    discourse:
      hosts:
        parkourvienna.at: {}
    prometheus:
      hosts:
        parkourvienna.at: {}
    grafana:
      hosts:
        parkourvienna.at: {}
