[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  network = "discourse"

[http.middlewares]
  [http.middlewares.www-redirect.redirectRegex]
    regex = "^http(s?)://www.{{discourse.site_domain}}/(.*)"
    replacement = "https://{{discourse.site_domain}}/${1}"  

[certificatesResolvers.default.acme]
  email = "{{ acme_email }}"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.default.acme.tlsChallenge]
