---
- name: create traefik directories
  file:
    path: "/var/traefik/acme"
    state: directory

- name: configure traefik
  template:
    src: "templates/traefik.toml"
    dest: "/var/traefik/traefik.toml"
  notify: restart_traefik

- import_role:
    name: cloudflight.systemd_service
