---
scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5
    # seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'discourse'
    static_configs:
      - targets: ['discourse:80']
